### PR TITLE
[WIP] Function validation from type specification.

### PR DESCRIPTION
**Pull request by NJichev**
Work in progress function validation.

### CODE REVIEW

**Comment by NJichev** [comment]
Some questions I have:
  - Should I split the validator code in it's own module? I think some stuff of the `Types` module can be reused, or there are functions that I'll need to make public.
  - The way validation is being done is `read type AST -> generate member function`, you can check the `validator_for` function - currently it looks as the `generate` function in the `Types` module, if the modules are merged, should I just return tuples with two elements in the `generate` function: `{%StreamData{}, member_function}`?
  - Also the tests will be duplicated, the way to test it is to get member function for a type and then generate the stream for this type and generate a stream of any elements with the type filtered-> and then check all that passing in elements from first stream return true, second stream return false. Generating the first stream of types is basically the tests for the type generators.

**Comment by NJichev** [comment]
Some other notes: currently I compose functions via `compose | one_of` - I think making them macros that rewrite the passed in list of functions would compose the functions compile time, so this is a TODO.

**Comment by whatyouhide** [comment]
I think for now, the best way is to have a `from_type` function like the one we have which just calls a `from_type_with_validator` function:

```elixir
def from_type_with_validator(type) do
  {generator, validator}
end

def from_type(type) do
  {generator, _validator} = from_type_with_validator(type)
  generator
end
```

The logic can be shared very closely. One thing you could experiment with is using https://github.com/whatyouhide/saul for creating the validators. So basically say you have to generate an integer:

```elixir
def from_type(:integer) do
  {StreamData.integer(), &is_integer/1}
end
```

and then you can validate with `Saul.validate/2`. This is just a thought but I think it would be interesting to experiment with this.

**Comment by NJichev** [comment]
Closed in favour of #20

**Pull request closed without merging**
